### ISSUE TITLE
How much of clojure / overtone is supported?

### ISSUE THREAD

**Issue by danbri** [ctford/klangmeister#2]
This is awesome :)

Could you share some notes on the http://ctford.github.io/klangmeister/ pages to set expectations for whether code snippets can be shared with overtone, and how much of clojure is available?

**Comment by ctford** [comment]
Hi,

Thanks for your feedback. I really appreciate you taking the time to make suggestions as well as to try out Klangmeister.

There are some very brief snippets on the "Reference" page. Is that the kind of thing you're after? I'm in two minds about a detailed discussion of Overtone in Klangmeister itself, as many users won't have done any Overtone.

In answer to your specific questions:
- Overtone code won't work because Klangmeister has its own way of doing synthesis that integrates with the browser's Web Audio API instead of the Supercollider synthesis engine that Overtone uses. I considered trying to make the Clojure API the same, but ended up inventing a new one rather than have one that almost worked but didn't. So expect to have to use `connect->` rather than `definst`.
- Arbitrary Clojurescript is fine to use in your music, though bear in mind that the synthesis functions aren't actually side effecting - they just return a synthesiser definition, so if you create two synthesisers e.g. in the body of a function, only the one you return will do anything. Same goes for the music - it just returns a note data structure.

Thanks.

**Comment by danbri** [comment]
Thanks, that was just the information I was missing out on :)

**Comment by ctford** [comment]
Cheers. I also added some more background to the README.

**Comment by danbri** [comment]
Is there anything that can be said about concurrency at this stage? (not being familiar with clojurescript but thinking about the likes of threads in Sonic Pi, Chuck, and in browser context, Promises, stratified js etc.)

**Comment by ctford** [comment]
Good question.

There isn't any, by design. Sonic Pi achieves polyphony by playing
different parts on different threads. Klangmeister does it by merging
together the lists of notes from both parts.

**Comment by danbri** [comment]
Thanks. I'll play around. Feel free to close out this issue unless you need it as a memory-jog for anything.
