### ISSUE TITLE
Feasability: sound.* namespaces standalone package

### ISSUE THREAD

**Issue by gamecubate** [ctford/klangmeister#3]
I'm not sure I understand the limitations of klangmeister insofar as using it in my project (for in-app web audio interfacing, sound fx and score generation) is concerned. It is not feasible if I understood correctly. 

Have you considered spawning off a project that would focus on your sound.\* namespaces? I've looked at other packages (hum, mantra, squelch) and they are not as advanced as yours.

**Comment by ctford** [comment]
Thanks for the encouragement.

I had considered it, but I haven't done it so far because I wanted the API to stabilise. I was also waiting for a little encouragement from people who might be interested in it, so thankyou for that. :-)

There is one enhancement that I'm in the middle of that I would probably want to complete before splitting out a standalone synthesis library - keeping track of both the input and output nodes of a synthesis tree (started in commit f1ace8d353ed5a813b767c6aea55160dc944e256 if you're interested).

Right now, I pass around the output node of a synth subtree, which generally works, but puts restrictions on the order that subgraphs are plugged together.

Having said that, the sound.\* namespaces could be repurposed for other projects as they are now - if you're willing to copy around files rather than pull in a proper dependency.

**Comment by gamecubate** [comment]
Encouragement is more than deserved. I am surprised that not a lot more people than now are talking about this. Nice lib; has simplicity _and_ heft. Feels just right. Thanks for your offer. If and when I use it (if time allows...) I'll be sure to attribute and share.

**Comment by gzmask** [comment]
I am definitely interested. If Ctford can make a screencast, I am sure this will be noticed by a lot more. I think the major selling point is the bootstrapped cljs, the possibilities are endless: i.e: multiplayer online music synthesis!! Even better, it only needs your mobile phone browser to work!

**Comment by ctford** [comment]
Good suggestion.

**Comment by ctford** [comment]
I started extracting the synthesis namespace [into its own project](https://github.com/ctford/klang), as that's all you would need to make sound in another Clojurescript context. However, I found that the name Klang is already [taken](https://github.com/rauhs/klang). Got any good suggestions? :-)

@gamecubate, does Klang look like it would be what you're after?

**Comment by gamecubate** [comment]
It does. To perfection. And I intend to initiate a project -- right after I finish the current one -- that will make good use of your lib. Thanks for the split. Too bad klang was already taken though. I have no (fresh) ideas as to how to name this new child.

**Comment by ctford** [comment]
I've extracted the synthesis namespace to its own small library - [CLJS Bach](https://github.com/ctford/cljs-bach). If you use it, let me know how it goes.

**Comment by gamecubate** [comment]
Thanks a lot for this. Will use it in a few days for a (game experiment) project. Will post as soon as.
