### ISSUE TITLE
Figwheel livecoding workflow instead of in-browser livecoding environment

### ISSUE THREAD

**Issue by gzmask** [ctford/klangmeister#9]
Can we have figwheel and probably Emacs/Vim as livecoding environment instead of doing stuff in the browser?

**Comment by ctford** [comment]
Klangmeister uses CLJS Bach, which works by running synthesisers based on
Web Audio. Sadly, that means we need the browser.

However, you could check out Leipzig, which uses Overtone for synthesis and
thus runs fine without a browser. I play it from Vim Fireplace.

I hope that helps.

El 14 feb. 2017 6:59 p. m., "gzmask" <notifications@github.com> escribió:

Can we have figwheel and probably Emacs/Vim as livecoding environment
instead of doing stuff in the browser?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ctford/klangmeister/issues/9>, or mute the thread

**Comment by gzmask** [comment]
sorry for not being clear enough. I know that this is web audio livecoding scratchpad. What I mean is that if it's possible to do the coding part in a emacs/vim environment instead of the browser, then lein figwheel will automatically inject the changes into browser.

So basically web browser acting like the server or supercolider, and klangmeister acting as client like overtone. This could make the library more like a livecoding platform maybe?
